use_frameworks!

platform :ios, '9.0'

target 'KcSwizzleManage_Example' do
  pod 'KcSwizzleManage', :path => '../'

  target 'KcSwizzleManage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
